"""Restaurant data for Aman Bhaiya Restaurant website.
Source: websiteinformtion.txt
"""

RESTAURANTS = {
    "casa-da-peixe": {
        "id": "casa-da-peixe",
        "name": "Peixe no Largo",
        "short_name": "Peixe no Largo",
        "tagline": "Fresh seafood and Portuguese coastal flavors",
        "type": "Seafood / Portuguese Coastal Cuisine",
        "description": (
            "Specializing in the freshest seafood and traditional Portuguese "
            "coastal cuisine. Our dishes celebrate the bounty of the sea with "
            "authentic recipes passed down through generations of fishermen "
            "and coastal cooks."
        ),
        "address_line_1": "Largo José Afonso 64, 2900-633",
        "address_line_2": "Setúbal, Portugal",
        "phone": "+351 935 540 297",
        "whatsapp": "+351 935 540 297",
        "email": "info@casadapeixe.pt",
        "orders_email": "lapicanha.setubal@gmail.com",
        "instagram": "@casadepeixe3",
        "instagram_url": "https://www.instagram.com/casadepeixe3/",
        "hours": [
            ("Monday", "CLOSED"),
            ("Tuesday", "12:00 PM - 10:00 PM"),
            ("Wednesday", "12:00 PM - 10:00 PM"),
            ("Thursday", "12:00 PM - 10:00 PM"),
            ("Friday", "12:00 PM - 11:00 PM"),
            ("Saturday", "12:00 PM - 11:00 PM"),
            ("Sunday", "12:00 PM - 9:00 PM"),
        ],
        "theme": {
            "primary": "#1B3A57",   # ocean blue
            "accent": "#C9A961",    # gold
            "bg": "#F5E9D4",        # cream
        },
        "hero_emoji": "🐟",
        "map_query": "Largo+José+Afonso+64+Setúbal+Portugal",
        "hero_image": "images/casa-da-peixe-cover.jpg",
        "logo_image": "images/casa-da-peixe-logo.jpg",
        "gallery": [
            ("images/casa-da-peixe-1.jpg", "Peixe no Largo signboard on the building exterior"),
            ("images/casa-da-peixe-2.jpg", "Outdoor seating area at Peixe no Largo"),
            ("images/casa-da-peixe-3.jpg", "Peixe no Largo circular logo on wood-panel wall"),
            ("images/casa-da-peixe-4.jpg", "Close-up of the Peixe no Largo branded sign"),
            ("images/casa-da-peixe-5.jpg", "Artisanal seafood platter with wine pairing"),
            ("images/casa-da-peixe-6.jpg", "Portuguese seafood croquettes with house sauce"),
            ("images/casa-da-peixe-7.jpg", "Golden seafood fritters with coastal flavors"),
            ("images/casa-da-peixe-8.jpg", "Traditional spring rolls with Portuguese twist"),
            ("images/casa-da-peixe-9.jpg", "Fresh fish with basil and roasted vegetables"),
            ("images/casa-da-peixe-10.jpg", "Close-up of traditional Portuguese seafood preparation"),
            ("images/casa-da-peixe-11.jpg", "Crispy spring rolls with sweet and sour sauce"),
            ("images/casa-da-peixe-12.jpg", "Seafood prawns in traditional Portuguese sauce"),
            ("images/casa-da-peixe-13.jpg", "Traditional fried cuttlefish julienne with herbs"),
            ("images/casa-da-peixe-14.jpg", "Another angle of the signature cuttlefish dish"),
            ("images/casa-da-peixe-15.jpg", "Portuguese seafood curry in traditional clay pot"),
        ],
        "menu": {
            "Couvert": [
                ("Cesto de Pão", "1.50€", "Bread basket"),
                ("Queijo Seco", "4.50€", "Portuguese dried cheese"),
                ("Queijo Fresco", "6.50€", "Fresh Portuguese cheese"),
                ("Azeitonas", "2.50€", "Portuguese olives"),
                ("Patês", "1.50€", "Portuguese pâtés"),
                ("Manteiga", "1.50€", "Butter"),
                ("Presunto", "11.00€", "Portuguese cured ham"),
            ],
            "Sopas (Soups)": [
                ("Sopa do Dia", "3.50€", "Daily soup"),
                ("Sopa de Peixe", "4.50€", "Traditional Portuguese fish soup"),
            ],
            "Entradas (Starters)": [
                ("Camarão ao Alhinho", "17.00€", "Garlic prawns"),
                ("Ameijoas ao Natural", "19.00€", "Natural clams"),
                ("Mexilhão à Original", "21.00€", "Original style mussels"),
                ("Lingueirão à Bolhão Pato", "21.00€", "Razor clams Bolhão Pato style"),
                ("Salada de Polvo", "8.00€", "Octopus salad"),
                ("Linguini de Camarão", "13.00€", "Prawn linguini"),
            ],
            "Peixe Grelhado à Dose (Grilled Fish - Portions)": [
                ("Pregado", "25.00€", "Grilled turbot portion"),
                ("Dourada", "18.00€", "Grilled sea bream portion"),
                ("Robalo", "18.00€", "Grilled sea bass portion"),
                ("Salmão", "24.00€", "Grilled salmon portion"),
                ("Peixe Espada", "19.00€", "Grilled scabbard fish"),
                ("Sardinhas", "15.00€", "Grilled sardines"),
                ("Choco Assado", "17.00€", "Roasted cuttlefish"),
                ("Lulas", "17.00€", "Grilled squid"),
                ("Atum", "25.00€", "Grilled tuna portion"),
                ("Bacalhau", "25.00€", "Grilled cod portion"),
            ],
            "Carne (Meat)": [
                ("Bitoque", "16.50€", "Portuguese steak with fried egg"),
                ("Tabua de Picanha", "39.90€", "Picanha sharing board"),
                ("Bife à Portuguesa", "18.00€", "Portuguese style steak"),
                ("Entrecote", "29.90€", "Grilled ribeye steak"),
                ("Plumas", "19.50€", "Iberian pork plumas"),
            ],
            "Menu": [
                ("Picanha à Discrição", "21.50€", "All-you-can-eat picanha"),
            ],
            "Tachos & Pratos": [
                ("Massa de Peixe", "35.00€", "Fish pasta"),
                ("Arroz de Marisco", "37.00€", "Seafood rice"),
                ("Cataplana", "50.00€", "Traditional seafood cataplana"),
                ("Atum de Cebolada", "24.00€", "Tuna with onions"),
                ("Choco à Algarvia", "16.00€", "Cuttlefish Algarve style"),
                ("Polvo à Lagareiro", "19.00€", "Octopus with olive oil and garlic"),
                ("Choco Frito", "18.50€", "Fried cuttlefish"),
                ("Bacalhau à Brás", "17.00€", "Shredded cod with eggs"),
                ("Arroz de Gambas", "22.50€", "Prawn rice"),
                ("Caril de Gambas", "24.50€", "Prawn curry"),
                ("Risotto de Camarão", "26.50€", "Prawn risotto"),
            ],
            "Sobremesas (Desserts)": [
                ("Cheesecake Baba de Camelo", "4.50€", "Camel drool cheesecake"),
                ("Cheesecake Frutos Vermelhos", "4.50€", "Red berries cheesecake"),
                ("Cheesecake Manga", "4.50€", "Mango cheesecake"),
                ("Bolo Brigadeiro", "4.50€", "Brazilian brigadeiro cake"),
                ("Bolo de Bolacha", "4.50€", "Cookie cake"),
                ("Pudim", "4.50€", "Portuguese pudding"),
                ("Musse de Chocolate", "4.50€", "Chocolate mousse"),
                ("Musse de Manga", "4.50€", "Mango mousse"),
                ("Doce da Casa", "4.50€", "House special dessert"),
                ("Fruta", "3.50€", "Fresh fruit"),
            ],
            "Cafetária": [
                ("Café", "1.20€", "Portuguese espresso"),
                ("Descafeinado", "1.20€", "Decaffeinated coffee"),
                ("Chá", "1.50€", "Tea"),
                ("Abatanado", "1.50€", "Abatanado coffee"),
                ("Meia de Leite", "2.00€", "Coffee with milk"),
                ("Irish Coffee", "5.00€", "Irish coffee"),
                ("Café Bombom", "6.50€", "Café bombom"),
            ],
            "Bebidas (Drinks)": [
                ("Água 1.5L", "3.00€", "Still water 1.5L"),
                ("Águas com Gás 1L", "2.70€", "Sparkling water 1L"),
                ("Água com Gás", "2.00€", "Sparkling water"),
                ("Água Garrafa 0.50cl", "1.50€", "Bottled water"),
                ("Ice Tea", "2.50€", "Iced tea"),
                ("Coca-Cola", "2.50€", "Coca-Cola"),
                ("Guaraná", "2.50€", "Guaraná soda"),
                ("Sumol", "2.50€", "Sumol"),
                ("Sumos Naturais", "3.00€", "Natural juices"),
                ("Sagres", "2.50€", "Portuguese beer"),
                ("Sagres Preta", "2.50€", "Dark Sagres"),
                ("Bandida do Pomar", "2.50€", "Craft beer"),
                ("Caneca Imperial", "4.00€", "Imperial mug"),
                ("Imperial", "2.50€", "Draft beer"),
            ],
            "Sangrias (1L / 2L)": [
                ("Branca", "14.90€ / 21.90€", "White sangria"),
                ("Tinta", "14.90€ / 21.90€", "Red sangria"),
                ("Espumante", "17.90€ / 24.90€", "Sparkling sangria"),
                ("Frutos Vermelhos", "17.90€ / 24.90€", "Red berries sangria"),
            ],
            "Jarros de Vinho (House Wine Pitchers)": [
                ("Branco - 1/4L", "3.00€", "House white, quarter litre"),
                ("Branco - 1/2L", "5.00€", "House white, half litre"),
                ("Branco - 1L", "8.00€", "House white, one litre"),
                ("Tinto - 1/4L", "3.00€", "House red, quarter litre"),
                ("Tinto - 1/2L", "5.00€", "House red, half litre"),
                ("Tinto - 1L", "8.00€", "House red, one litre"),
            ],
            "Bebidas Alcoolicas (Spirits)": [
                ("Moscatel", "3.50€", ""),
                ("Licor Beirão", "4.50€", ""),
                ("Amêndoa Amarga", "3.50€", ""),
                ("CRF", "5.00€", ""),
                ("Velho Terra", "4.50€", ""),
                ("Baileys", "5.00€", ""),
                ("Macieira", "5.00€", ""),
                ("Logan", "10.00€", ""),
                ("Bushmills", "5.00€", ""),
                ("Famous Grouse", "5.00€", ""),
                ("Jameson", "5.00€", ""),
                ("J&B 15 Anos Reserva", "12.00€", ""),
            ],
            "Vinho Tinto (Red Wines)": [
                ("Grainha", "22.00€", ""),
                ("Costa Boal", "25.00€", ""),
                ("Casa da Passarella", "25.00€", ""),
                ("Monte dos Perdigões", "32.00€", ""),
                ("Quinta da Vacaria Reserva", "92.00€", ""),
                ("Manoella", "25.00€", ""),
                ("Mainova", "25.00€", ""),
                ("Duas Margens Reserva", "18.00€", ""),
                ("Assobio", "16.00€", ""),
                ("Terras do Grifo", "28.00€", ""),
                ("Cartuxa", "32.00€", ""),
                ("Plansel", "25.00€", ""),
                ("Grous", "25.00€", ""),
                ("Convento da Tomina", "25.00€", ""),
                ("Monte da Peceguinha", "21.00€", ""),
                ("Monte Velho Reserva", "18.00€", ""),
                ("Guarda Rios", "22.00€", ""),
                ("Reguengos", "16.00€", ""),
                ("Quinta do Carmo", "32.00€", ""),
                ("Monte das Servas", "16.00€", ""),
                ("Adega Mayor Reserva", "21.00€", ""),
                ("Scala Coeli", "95.00€", ""),
                ("Sobroso Reserva", "25.00€", ""),
                ("Coelheiros", "25.00€", ""),
                ("Monte dos Pinheiros", "16.00€", ""),
                ("Humanitas Reserva", "24.00€", ""),
                ("Ermelinda Reserva", "16.00€", ""),
                ("Ermelinda Cabernet", "19.00€", ""),
                ("Ermelinda Syrah", "18.00€", ""),
                ("Ermelinda", "12.00€", ""),
            ],
            "Vinho Branco (White Wines)": [
                ("Catarina", "13.00€", ""),
                ("Ermelinda", "12.00€", ""),
                ("Ermelinda Reserva", "16.00€", ""),
                ("Ermelinda Sauvignon Blanc", "19.00€", ""),
                ("Terras do Grifo", "16.00€", ""),
                ("Grainha Reserva", "18.00€", ""),
                ("Passadouro", "16.00€", ""),
                ("Costa Boal", "25.00€", ""),
                ("Casa de Santar", "22.00€", ""),
                ("Plansel", "18.00€", ""),
                ("Herdade do Grous", "22.00€", ""),
                ("Monte das Servas", "16.00€", ""),
                ("Comenda Grande", "15.00€", ""),
                ("Serra do Louro", "15.00€", ""),
                ("Reguengos Seleção", "12.00€", ""),
                ("Adega Mayor Reserva", "17.00€", ""),
                ("Cartuxa", "25.00€", ""),
                ("Scala Coeli", "65.00€", ""),
                ("Planalto", "18.00€", ""),
                ("Duas Margens Reserva", "18.00€", ""),
                ("CARM", "25.00€", ""),
                ("Quinta da Vacaria Reserva", "75.00€", ""),
                ("Grandes Quintas", "25.00€", ""),
                ("Ermelinda Verdelho", "18.00€", ""),
                ("Ermelinda Terras do Po Reserva", "19.00€", ""),
                ("BSE", "18.00€", ""),
                ("Ervideira", "24.00€", ""),
                ("Quinta do Carmo", "25.00€", ""),
            ],
            "Vinho Rosé": [
                ("Mateus", "16.00€", ""),
                ("Rose Pom Pom", "18.00€", ""),
                ("Ermelinda Rose", "16.00€", ""),
                ("Catarina Rose", "16.00€", ""),
            ],
            "Vinho Verde": [
                ("Campo da Vinha", "12.00€", ""),
                ("Casa de Vilacetinho", "24.00€", ""),
                ("Campo da Vinha (alt)", "11.00€", ""),
                ("Soalheiro", "18.00€", ""),
            ],
        },
        "policies": [
            "Os preços incluem a taxa de IVA em vigor. (Prices include VAT)",
            "Couvert is optional and cannot be charged unless requested or used.",
            "The establishment has a complaints book (livro de reclamações).",
            "Unpackaged food items, once chosen and delivered, are considered purchased.",
            "Allergen information available on request from staff.",
        ],
    },

    "lapicanha": {
        "id": "lapicanha",
        "name": "Lapicanha",
        "short_name": "Lapicanha",
        "tagline": "Premium grilled meats and traditional flavors",
        "sub_tagline": "A MEAT RESTAURANT",
        "type": "Premium Grill / Steakhouse / Portuguese-Brazilian Fusion",
        "description": (
            "Premium grilled meats and traditional Portuguese flavors in a warm, "
            "rustic atmosphere. We specialize in perfectly prepared picanha and "
            "other prime cuts, paired with authentic Portuguese sides and wines."
        ),
        "address_line_1": "Rua José Afonso nº 69",
        "address_line_2": "Setúbal, Portugal",
        "phone": "+351 935 540 297",
        "whatsapp": "+351 935 540 297",
        "email": "reservas@lapicanha.pt",
        "orders_email": "lapicanha.setubal@gmail.com",
        "instagram": "",
        "instagram_url": "",
        "hours": [
            ("Monday", "6:00 PM - 11:00 PM"),
            ("Tuesday", "6:00 PM - 11:00 PM"),
            ("Wednesday", "6:00 PM - 11:00 PM"),
            ("Thursday", "6:00 PM - 11:00 PM"),
            ("Friday", "6:00 PM - 12:00 AM"),
            ("Saturday", "6:00 PM - 12:00 AM"),
            ("Sunday", "6:00 PM - 10:00 PM"),
        ],
        "theme": {
            "primary": "#8B1A1A",   # deep wine red
            "accent": "#D4AF37",    # gold
            "bg": "#F5E9D4",        # cream
        },
        "hero_emoji": "🥩",
        "map_query": "Rua+José+Afonso+69+Setúbal+Portugal",
        "hero_image": "images/lapicanha-hero.png",
        "logo_image": "images/lapicanha-cover.jpg",
        "gallery": [
            ("images/gallery-1.jpg", "Red cocktails and cozy bar atmosphere"),
            ("images/gallery-2.jpg", "Beautiful picanha spread with sides and wine"),
            ("images/gallery-3.jpg", "Tender meat stew with wine and bread"),
            ("images/gallery-4.jpg", "Grilled meat skewers with beer and sides"),
            ("images/gallery-5.jpg", "Traditional picanha in copper pan with Portuguese cider"),
            ("images/gallery-6.jpg", "Signature meat stew presentation"),
            ("images/gallery-7.jpg", "Golden picanha slices with premium wine"),
            ("images/gallery-8.jpg", "Gourmet pasta with Portuguese cider"),
            ("images/gallery-9.jpg", "Colorful meat and fruit platter with cocktails"),
            ("images/gallery-10.jpg", "Traditional meat board with chimichurri and sides"),
            ("images/gallery-11.jpg", "Bartenders serving fresh passion fruit cocktails"),
        ],
        "menu": {
            "Entradas (Starters)": [
                ("Cesto de Pão (2 unidades)", "1.50€", "Bread basket (2 units)"),
                ("Queijo Seco", "4.50€", "Dry cheese"),
                ("Queijo Amanteigado", "6.50€", "Buttery cheese"),
                ("Azeitonas", "3.50€", "Olives"),
                ("Crepes La Picanha", "5.00€", "Spring rolls"),
                ("Manteiga", "1.00€", "Butter"),
                ("Presunto", "10.00€", "Ham"),
                ("Pica Pau", "4.50€", "Woodpecker - cooked picanha with sauce"),
            ],
            "Pratos (Main Dishes)": [
                ("Hamburger no Prato", "14.90€", "Rice, fries and beans"),
                ("Hamburguer Vegano", "15.90€", "Vegan burger with rice and fries"),
                ("Hamburger La Picanha", "15.90€", "Burger with fried onion, bacon, cheddar, tomato and fries"),
                ("Espetada de Picanha", "15.90€", "Grilled picanha chunks with chorizo, rice and fries"),
                ("Frango à La Picanha", "18.90€", "Chicken stuffed with bacon and cheddar, garlic-herb sauce, rice, salad, fries"),
                ("Bife de Frango", "15.90€", "Grilled chicken steak with rice and fries"),
                ("Picanha à Discrição", "19.50€", "All-you-can-eat picanha with rice, beans, fries, salad and farofa"),
            ],
            "Nacos na Tabua (Premium Cuts)": [
                ("Premium Entrecôte (350g)", "24.90€", "Rice, beans and fries"),
                ("Premium Picanha (350g)", "24.90€", "Fries, rice and beans"),
            ],
            "Menu Executivo (Business Lunch)": [
                ("Picanha no Prato", "15.00€", "Mon-Fri lunch only (except holidays). Includes drink + coffee"),
            ],
            "Menu Infantil (Children 4-9)": [
                ("Frango à La Picanha", "10.50€", "Rice and fries"),
                ("Picanha no Prato", "10.50€", "Rice and fries"),
            ],
            "Sobremesas (Desserts)": [
                ("Cheesecake Oreo", "5.00€", ""),
                ("Cheesecake Frutos Vermelhos", "4.50€", "Red berries cheesecake"),
                ("Cheesecake Caramelo Salgado", "5.00€", "Salted caramel cheesecake"),
                ("Bolo Brigadeiro", "4.50€", "Brigadeiro cake"),
                ("Cheesecake Lima", "4.50€", "Lime cheesecake"),
                ("Bolo de Bolacha", "4.50€", "Cookie cake"),
                ("Petit Gateau c/ Gelado", "5.50€", "Petit gateau with ice cream"),
                ("Caixa Lisboetas", "13.00€", "Lisbon box dessert"),
                ("Pudim", "4.50€", "Pudding"),
                ("Musse de Chocolate", "4.50€", "Chocolate mousse"),
                ("Doce da Casa", "4.50€", "House sweet"),
                ("Bola de Gelado", "2.50€", "Ice cream scoop"),
            ],
            "Cafetária": [
                ("Café", "1.20€", ""),
                ("Descafeinado", "1.20€", "Decaf"),
                ("Chá", "1.50€", "Tea"),
                ("Abatanado", "1.50€", ""),
                ("Meia de Leite", "2.00€", "Coffee with milk"),
                ("Irish Coffee", "5.00€", ""),
                ("Café Bombom", "6.50€", ""),
            ],
            "Drinks": [
                ("Água Purificada", "2.70€", "Purified water"),
                ("Águas com Gás Purificada", "2.70€", "Purified sparkling water"),
                ("Água com Gás", "2.20€", "Sparkling water"),
                ("Água Garrafa 0.50cl", "1.70€", "Bottled water 0.5L"),
                ("Ice Tea", "2.20€", ""),
                ("Coca-Cola", "2.20€", ""),
                ("Guaraná", "2.20€", ""),
                ("Sumol", "2.20€", ""),
                ("Compal", "2.00€", ""),
            ],
            "Beers": [
                ("Sagres", "2.20€", ""),
                ("Sagres Preta", "2.50€", "Dark Sagres"),
                ("Sagres Zero", "2.50€", "Alcohol-free"),
                ("Sagres Bohemia", "2.50€", ""),
                ("Bandida do Pomar", "2.50€", "Craft beer"),
                ("Caneca Heineken", "4.00€", "Heineken mug"),
                ("Imperial Heineken", "2.50€", "Draft Heineken"),
            ],
            "Red Wines": [
                ("Dona Ermelinda", "12.00€", ""),
                ("Dona Ermelinda Reserva", "15.00€", ""),
                ("Ermelinda Syrah Reserva", "16.00€", ""),
                ("Quinta da Mimosa", "17.00€", ""),
                ("Herdade dos Grous", "20.00€", ""),
                ("Herdade dos Grous Reserva", "45.00€", ""),
                ("Assobio", "10.00€", ""),
                ("Monte Velho", "12.00€", ""),
                ("CARM", "13.00€", ""),
                ("CARM Reserva", "22.00€", ""),
                ("Caiado", "12.00€", ""),
                ("Touringa Nacional", "17.00€", ""),
                ("Altitude Reserva", "25.00€", ""),
                ("Pai Chão", "90.00€", "Premium selection"),
                ("Papa Figos", "15.00€", ""),
                ("Cartuxa", "35.00€", ""),
            ],
            "White Wines": [
                ("Dona Ermelinda Reserva", "15.00€", ""),
                ("Herdade dos Grous", "20.00€", ""),
                ("Assobio", "12.00€", ""),
                ("Monte Velho", "12.00€", ""),
                ("Caiado", "12.00€", ""),
                ("Touringa Nacional", "17.00€", ""),
                ("Papa Figos", "15.00€", ""),
                ("Altitude Reserva", "27.00€", ""),
                ("Herdade dos Grous Reserva", "30.00€", ""),
            ],
            "Rosé Wines": [
                ("Mateus", "12.00€", ""),
                ("Caiado Rosé", "10.00€", ""),
            ],
            "Sangrias (1L / 2L)": [
                ("Branca", "14.90€ / 21.90€", "White sangria"),
                ("Tinta", "14.90€ / 21.90€", "Red sangria"),
                ("Espumante", "17.90€ / 24.90€", "Sparkling sangria"),
                ("Frutos Vermelhos", "17.90€ / 24.90€", "Red berries"),
                ("Manga e Maracujá", "17.90€ / 24.90€", "Mango passion fruit"),
                ("Tropical", "17.90€ / 24.90€", "Tropical"),
            ],
            "Spirits": [
                ("Moscatel", "3.50€", ""),
                ("Licor Beirão", "4.50€", ""),
                ("Amêndoa Amarga", "3.50€", ""),
                ("CRF", "5.00€", ""),
                ("Velho Terra", "4.50€", ""),
                ("Malibu", "5.00€", ""),
                ("Baileys", "5.00€", ""),
                ("Macieira", "5.00€", ""),
                ("Logan", "10.00€", ""),
                ("Bushmills", "5.00€", ""),
                ("Famous Grouse", "5.00€", ""),
                ("Jameson", "5.00€", ""),
                ("Cutty Sark", "4.50€", ""),
                ("J&B 15 Anos Reserva", "12.00€", ""),
            ],
            "Cocktails": [
                ("Cocktail sem Álcool", "6.00€", "Non-alcoholic cocktail"),
                ("Caipirinha", "6.00€", ""),
                ("Caipiblack", "6.00€", ""),
                ("Marguerita", "8.00€", ""),
                ("Mojito", "8.00€", ""),
                ("Apérol Spritz", "6.00€", ""),
                ("Martini", "3.50€", ""),
                ("Bombay", "8.00€", ""),
                ("Beefeater Pink", "8.00€", ""),
                ("Beefeater", "8.00€", ""),
                ("Tanqueray", "8.00€", ""),
            ],
        },
        "policies": [
            "TODOS OS PRATOS SÃO INDIVIDUAIS. (All dishes are individual portions.)",
            "Menu Infantil: Children aged 4 to 9. Full price charged from age 10.",
            "Menu Executivo: Monday to Friday lunches only, except holidays.",
            "Waste Tax: Applied to customers who order too many Picanha à Discrição refills without the intent of consumption.",
            "May Special: Mother's Day - Picanha à Discrição with all sides included for just 18.50€",
        ],
    },
}


def get_restaurant(slug):
    return RESTAURANTS.get(slug)


def all_restaurants():
    return list(RESTAURANTS.values())
